services:
  database:
    image: postgres:17.4-alpine
    container_name: pg-db
    volumes:
      - pg_db:/var/lib/postgresql/data:rw
      - /tmp/postgres-tmp:/tmp:tmpfs
    networks:
      - backend-network
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres  -c max_connections=1000
                -c shared_buffers=256MB
                -c effective_cache_size=768MB
                -c maintenance_work_mem=64MB
                -c checkpoint_completion_target=0.7
                -c wal_buffers=16MB
                -c default_statistics_target=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-bot
    volumes:
      - app-logs:${LOG_DDIR:-/var/log/tb}
      - static-volume:/app/static:ro
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: ${POSTGRES_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PSWD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      LOG_DIR: ${LOG_DDIR:-/var/log/tb}
    env_file:
      - .env

volumes:
  app-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOG_SDIR:-./logs}
  static-volume:
    driver: local
  pg_db:

networks:
  backend-network:
    driver: bridge
    attachable: true
