"""
This module initializes and exports middleware components for the bot.

Modules:
    throttle: Contains the `AdvancedThrottleMiddleware` class, which is responsible
              for rate-limiting and throttling requests to ensure proper handling of
              incoming traffic.
    translation: Contains the `SimpleI18nMiddleware` class, which provides
              internationalization and localization support for the bot.
Exports:
    ThrottleMiddleware: Middleware for handling request throttling.
    IncludeHelper: Helper class for registering middlewares to routers.
"""
import sys
import logging

from enum import IntFlag, unique
from typing import Protocol, Tuple, TypeVar, Optional, List, Self, overload, runtime_checkable

from aiogram import BaseMiddleware, Router
from aiogram.utils.i18n import SimpleI18nMiddleware
from aiogram.dispatcher.event.telegram import TelegramEventObserver

from bot.middlewares.throttle import AutoTunedThrottlingMiddleware
from bot.middlewares.authoriz import AuthorizationMiddleware


AnyRouter = TypeVar("AnyRouter", Router, List[Router])
MiddlewareItem = TypeVar("MiddlewareItem", BaseMiddleware, Tuple[BaseMiddleware])

@unique
class EventObserverType(IntFlag):
    MESSAGES = 1
    CALLBACKS = 2

    @property
    def observer_attr(self) -> str:
        mapping = {
            EventObserverType.MESSAGES: "message",
            EventObserverType.CALLBACKS: "callback_query",
        }
        return mapping[self]
    
    @classmethod
    def all_flags(cls) -> List[Self]:
        return [flag for flag in cls]


@runtime_checkable
class IncludeMeta(Protocol):
    """
    Meta class to define the structure of inner middlewares for the current module.
    """
    class AutoTunedThrottlingMiddleware(AutoTunedThrottlingMiddleware):
        ...
    class AuthorizationMiddleware(AuthorizationMiddleware):
        ...
    class SimpleI18nMiddleware(SimpleI18nMiddleware):
        ...


@runtime_checkable
class MiddlewareFactory(Protocol):
    """
    MiddlewareFactory is a protocol that defines a callable interface for creating
    a list of middleware instances. Classes or functions implementing this protocol
    should accept a module of type `IncludeMeta` and return a list of `BaseMiddleware`
    instances.

    Methods:
        __call__(module: Type[IncludeMeta]) -> List[BaseMiddleware]:
            A callable method that takes a module of type `IncludeMeta` and returns
            a list of middleware instances.
    """
    def __call__(
        self,
        module: IncludeMeta,
        *,
        types: Optional[EventObserverType]
    ) -> List[MiddlewareItem]:
        ...


class IncludeHelper:
    def __init__(self, factory: MiddlewareFactory,
                 outer_middleware: bool = True) -> None:
        """
        Initializes the middleware with the given factory and configuration.
        
        Args:
            factory (MiddlewareFactory): The factory responsible for creating middleware instances.
            outer_middleware (bool, optional): Indicates whether the middleware is an outer middleware. 
                Defaults to True.
        """
        self.logger = logging.getLogger(__name__)
        self.logger.info(f"Registering middlewares for {__package__}")
        self.factory = factory
        self.outer_middleware = outer_middleware

    @overload
    def __rmatmul__(self, router: Router) -> bool:
        ...
    
    @overload
    def __rmatmul__(self, routers: List[Router]) -> bool:
        ...

    def __rmatmul__(self, batch: AnyRouter) -> bool:
        """
        Implements the reverse matrix multiplication operator (`@`) for registering middlewares
        to a router.
        This method is invoked when the `@` operator is used with the router on the left-hand side
        and an instance of this class on the right-hand side. It attempts to register all middlewares
        provided by the `self.factory` method to the appropriate middleware target in the router.

        Args:
            batch (AnyRouter): The router instance('s) to which the middlewares will be registered.

        Returns:
            bool: True if all middlewares were successfully registered, False otherwise.

        Behavior:
            - Iterates through the middlewares generated by `self.factory`.
            - Determines the target middleware based on whether `self.outer_middleware` is set.
            - Registers each middleware to the determined target middleware.
            - Logs the registration of each middleware.
            - Catches and logs any exceptions that occur during the registration process.
            
        Exceptions:
            - Logs a warning if an error occurs during middleware registration and returns False.
        """
        not isinstance(batch, List) and (batch := (batch,))

        try:
            module: IncludeMeta = sys.modules[__name__]

            items = ((_ := self.factory).__code__.co_argcount > 1) and \
                _(module, EventObserverType) or _(module)

            for router in batch:
                for item in items:
                    if isinstance(item, Tuple):
                        mw, et = item
                        list(map(
                            lambda flag: self._register_mw(router, flag, mw),
                            filter(lambda flag: et & flag, EventObserverType.all_flags())
                        ))
                    else:
                        list(map(
                            lambda flag: self._register_mw(router, flag, item),
                            EventObserverType.all_flags()
                        ))
            return True
        except Exception as e:
            self.logger.warning(f"Error while registering middlewares: {e}", exc_info=True)
            return False
        
    def _register_mw(
        self,
        router: Router,
        et: EventObserverType,
        mw: BaseMiddleware
    ) -> None:
        observer: TelegramEventObserver = getattr(router, et.observer_attr)

        mw_pool = self.outer_middleware and \
            observer.outer_middleware or observer.middleware

        mw_pool.register(mw)

        self.logger.info(f"Registered middleware: {mw}")


__all__ = [
    "AutoTunedThrottlingMiddleware",
    "AuthorizationMiddleware",
    "SimpleI18nMiddleware",
    "IncludeHelper",
]
